title: Alfred Etornam Klu
description: A minimal blog
baseurl: ""
url: ""

markdown: kramdown
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .idea/
